/**
 * 本文件定义摄像头接口相关的调用
 */
syntax = "proto2";
option optimize_for = LITE_RUNTIME;
option java_package = "com.epoch.classup.jsinterface.proto.source";
option java_outer_classname = "WebCameraProto";
option objc_class_prefix = "EPO";

package BridgeProto;
// --------------- web 消息 ----------------------

/**
 * 相机摄像头类型。
 *
 * 参数：
 * FRONT: 前置摄像头（移动端用）
 * BACK: 后置摄像头（移动端用)
 * COMMON: 普通可用摄像头（桌面端用）
 */
enum CameraType {
  FRONT = 0;
  BACK = 1;
  COMMON = 2;
}

/**
 * 摄像头信息
 * 目前只有CameraType和name，后续根据业务需要可以扩展字段
 *
 * 参数：
 * name：摄像头的名称，移动端可以传摄像头的编号
 * type：摄像头的类型，详见[CameraType]
 */
message CameraInfo {
  required string name = 1;
  optional CameraType type = 2;
  required string log = 3;
}