// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: camera.proto

package org.example.source;

public final class WebCameraProto {
  private WebCameraProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * <pre>
   **
   * 相机摄像头类型。
   * 参数：
   * FRONT: 前置摄像头（移动端用）
   * BACK: 后置摄像头（移动端用)
   * COMMON: 普通可用摄像头（桌面端用）
   * </pre>
   *
   * Protobuf enum {@code BridgeProto.CameraType}
   */
  public enum CameraType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>FRONT = 0;</code>
     */
    FRONT(0),
    /**
     * <code>BACK = 1;</code>
     */
    BACK(1),
    /**
     * <code>COMMON = 2;</code>
     */
    COMMON(2),
    ;

    /**
     * <code>FRONT = 0;</code>
     */
    public static final int FRONT_VALUE = 0;
    /**
     * <code>BACK = 1;</code>
     */
    public static final int BACK_VALUE = 1;
    /**
     * <code>COMMON = 2;</code>
     */
    public static final int COMMON_VALUE = 2;


    @java.lang.Override
    public final int getNumber() {
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CameraType valueOf(int value) {
      return forNumber(value);
    }

    public static CameraType forNumber(int value) {
      switch (value) {
        case 0: return FRONT;
        case 1: return BACK;
        case 2: return COMMON;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CameraType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CameraType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CameraType>() {
            @java.lang.Override
            public CameraType findValueByNumber(int number) {
              return CameraType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return CameraTypeVerifier.INSTANCE;
    }

    private static final class CameraTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new CameraTypeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return CameraType.forNumber(number) != null;
            }
          };

    private final int value;

    private CameraType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:BridgeProto.CameraType)
  }

  public interface CameraInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BridgeProto.CameraInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string name = 1;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required .BridgeProto.CameraType type = 2;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>required .BridgeProto.CameraType type = 2;</code>
     * @return The type.
     */
    WebCameraProto.CameraType getType();

    /**
     * <code>optional string log = 3;</code>
     * @return Whether the log field is set.
     */
    boolean hasLog();
    /**
     * <code>optional string log = 3;</code>
     * @return The log.
     */
    java.lang.String getLog();
    /**
     * <code>optional string log = 3;</code>
     * @return The bytes for log.
     */
    com.google.protobuf.ByteString
        getLogBytes();
  }
  /**
   * <pre>
   **
   * 摄像头信息
   * 目前只有CameraType和name，后续根据业务需要可以扩展字段
   * 参数：
   * name：摄像头的名称，移动端可以传摄像头的编号
   * type：摄像头的类型，详见[CameraType]
   * </pre>
   *
   * Protobuf type {@code BridgeProto.CameraInfo}
   */
  public  static final class CameraInfo extends
      com.google.protobuf.GeneratedMessageLite<
          CameraInfo, CameraInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:BridgeProto.CameraInfo)
      CameraInfoOrBuilder {
    private CameraInfo() {
      name_ = "";
      log_ = "";
    }
    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.String name_;
    /**
     * <code>required string name = 1;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>required string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>required string name = 1;</code>
     * @param value The name to set.
     */
    private void setName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      name_ = value;
    }
    /**
     * <code>required string name = 1;</code>
     */
    private void clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>required string name = 1;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      name_ = value.toStringUtf8();
      bitField0_ |= 0x00000001;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>required .BridgeProto.CameraType type = 2;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required .BridgeProto.CameraType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public WebCameraProto.CameraType getType() {
      WebCameraProto.CameraType result = WebCameraProto.CameraType.forNumber(type_);
      return result == null ? WebCameraProto.CameraType.FRONT : result;
    }
    /**
     * <code>required .BridgeProto.CameraType type = 2;</code>
     * @param value The type to set.
     */
    private void setType(WebCameraProto.CameraType value) {
      type_ = value.getNumber();
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>required .BridgeProto.CameraType type = 2;</code>
     */
    private void clearType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      type_ = 0;
    }

    public static final int LOG_FIELD_NUMBER = 3;
    private java.lang.String log_;
    /**
     * <code>optional string log = 3;</code>
     * @return Whether the log field is set.
     */
    @java.lang.Override
    public boolean hasLog() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string log = 3;</code>
     * @return The log.
     */
    @java.lang.Override
    public java.lang.String getLog() {
      return log_;
    }
    /**
     * <code>optional string log = 3;</code>
     * @return The bytes for log.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLogBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(log_);
    }
    /**
     * <code>optional string log = 3;</code>
     * @param value The log to set.
     */
    private void setLog(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000004;
      log_ = value;
    }
    /**
     * <code>optional string log = 3;</code>
     */
    private void clearLog() {
      bitField0_ = (bitField0_ & ~0x00000004);
      log_ = getDefaultInstance().getLog();
    }
    /**
     * <code>optional string log = 3;</code>
     * @param value The bytes for log to set.
     */
    private void setLogBytes(
        com.google.protobuf.ByteString value) {
      log_ = value.toStringUtf8();
      bitField0_ |= 0x00000004;
    }

    public static WebCameraProto.CameraInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WebCameraProto.CameraInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WebCameraProto.CameraInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WebCameraProto.CameraInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WebCameraProto.CameraInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WebCameraProto.CameraInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WebCameraProto.CameraInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static WebCameraProto.CameraInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static WebCameraProto.CameraInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static WebCameraProto.CameraInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static WebCameraProto.CameraInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static WebCameraProto.CameraInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(WebCameraProto.CameraInfo prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     **
     * 摄像头信息
     * 目前只有CameraType和name，后续根据业务需要可以扩展字段
     * 参数：
     * name：摄像头的名称，移动端可以传摄像头的编号
     * type：摄像头的类型，详见[CameraType]
     * </pre>
     *
     * Protobuf type {@code BridgeProto.CameraInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          WebCameraProto.CameraInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:BridgeProto.CameraInfo)
        WebCameraProto.CameraInfoOrBuilder {
      // Construct using org.example.proto.com.epoch.classup.jsinterface.proto.source.WebCameraProto.CameraInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required string name = 1;</code>
       * @return Whether the name field is set.
       */
      @java.lang.Override
      public boolean hasName() {
        return instance.hasName();
      }
      /**
       * <code>required string name = 1;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>required string name = 1;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>required string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>required .BridgeProto.CameraType type = 2;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override
      public boolean hasType() {
        return instance.hasType();
      }
      /**
       * <code>required .BridgeProto.CameraType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public WebCameraProto.CameraType getType() {
        return instance.getType();
      }
      /**
       * <code>required .BridgeProto.CameraType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setType(WebCameraProto.CameraType value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>required .BridgeProto.CameraType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <code>optional string log = 3;</code>
       * @return Whether the log field is set.
       */
      @java.lang.Override
      public boolean hasLog() {
        return instance.hasLog();
      }
      /**
       * <code>optional string log = 3;</code>
       * @return The log.
       */
      @java.lang.Override
      public java.lang.String getLog() {
        return instance.getLog();
      }
      /**
       * <code>optional string log = 3;</code>
       * @return The bytes for log.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLogBytes() {
        return instance.getLogBytes();
      }
      /**
       * <code>optional string log = 3;</code>
       * @param value The log to set.
       * @return This builder for chaining.
       */
      public Builder setLog(
          java.lang.String value) {
        copyOnWrite();
        instance.setLog(value);
        return this;
      }
      /**
       * <code>optional string log = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLog() {
        copyOnWrite();
        instance.clearLog();
        return this;
      }
      /**
       * <code>optional string log = 3;</code>
       * @param value The bytes for log to set.
       * @return This builder for chaining.
       */
      public Builder setLogBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLogBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BridgeProto.CameraInfo)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new WebCameraProto.CameraInfo();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "name_",
              "type_",
              WebCameraProto.CameraType.internalGetVerifier(),
              "log_",
            };
            java.lang.String info =
                "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0002\u0001\u1508\u0000\u0002" +
                "\u150c\u0001\u0003\u1008\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<WebCameraProto.CameraInfo> parser = PARSER;
          if (parser == null) {
            synchronized (WebCameraProto.CameraInfo.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<WebCameraProto.CameraInfo>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:BridgeProto.CameraInfo)
    private static final WebCameraProto.CameraInfo DEFAULT_INSTANCE;
    static {
      CameraInfo defaultInstance = new CameraInfo();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        CameraInfo.class, defaultInstance);
    }

    public static WebCameraProto.CameraInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CameraInfo> PARSER;

    public static com.google.protobuf.Parser<CameraInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
